title: Course Syllabi Collection
description: Automatically synced syllabi from various courses
theme: minima
markdown: kramdown
highlighter: rouge
permalink: /:basename.html
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  active:
    output: true
    permalink: /active/:name.html
  proposed:
    output: true
    permalink: /proposed/:name.html

defaults:
  - scope:
      path: ""
      type: "active"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "proposed"
    values:
      layout: "default"

header_pages:
show_excerpts: false
