title: Course Syllabi Collection
description: Automatically synced syllabi from various courses
baseurl: /syllabi
theme: minima
markdown: kramdown
highlighter: rouge

# Enable MathJax support
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
permalink: /:basename.html
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-last-modified-at

exclude:
  - docs/

collections:
  active:
    output: true
    permalink: /:name.html
  proposed:
    output: true
    permalink: /proposed/:name.html

defaults:
  - scope:
      path: ""
      type: "active"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "proposed"
    values:
      layout: "default"

header_pages:
show_excerpts: false
